### 服务器配置
server:
    port: 4397
    tomcat.uri-encoding: UTF-8
###  context-path: /vcoinb

### mybatis配置
mybatis:
    type-aliases-package: lzlzgame.dao.entity
    mapper-locations: classpath:mapper/*.xml
mapper:
    not-empty: false
    identity: MYSQL
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

### spring配置
spring:
    ###禁用默认favicon
    mvc.favicon.enabled: false
    http:
        encoding.charset: UTF-8
        encoding.force: true
    ##模板引擎
    thymeleaf:
        cache: false #开发时禁止缓存
        prefix: classpath:/templates/
        suffix: .html
        encoding: UTF-8
        content-type: text/html
        mode: HTML5
    ##redis
    redis:
        database: 0
        host: 127.0.0.1
        port: 36379
        password: 123456
    ##数据库连接
    datasource:
        url: jdbc:mysql://47.98.143.33:3306/lz?useSSL=false&amp;useUnicode=true&amp;characterEncoding=utf-8&amp;allowMultiQueries=true
        username: root
        password: QWERDF595182653
        driver-class-name: com.mysql.jdbc.Driver
###日志
logging:
    level:
        root: info
myYml:
    simpleProp: simplePropValue
    arrayProps: 1,2,3,4,5
    listProp1:
        - name: abc
          value: abcValue
        - name: efg
          value: efgValue
    listProp2:
        - config2Value1
        - config2Vavlue2
    mapProps:
        key1: value1
        key2: value2